"""Apply project MCP overrides to generated Codex config and lock data."""

from collections.abc import Mapping, MutableMapping
from typing import Any

from .mcp_fields import known_fields
from .toml_io import ensure_toml_table


def apply_mcp_overrides(
    codex_config: MutableMapping[str, Any],
    overrides: Mapping[str, Mapping[str, Any]],
    previous_lock: Mapping[str, Any],
) -> None:
    """Apply MCP overrides to a local Codex config document.

    Args:
        codex_config: Mutable .codex/config.toml document.
        overrides: Current MCP overrides.
        previous_lock: Previous codexmgr lock data.
    """
    mcp_servers = ensure_toml_table(
        codex_config,
        "mcp_servers",
        ".codex/config.toml [mcp_servers] must be a table",
    )
    _remove_previous_fields(mcp_servers, previous_lock)
    for server_id, fields in overrides.items():
        target = ensure_toml_table(
            mcp_servers,
            server_id,
            f".codex/config.toml mcp_servers.{server_id} must be a table",
        )
        target.update(known_fields(fields))


def mcp_lock_data(overrides: Mapping[str, Mapping[str, Any]]) -> dict[str, Any]:
    """Build lock data for MCP overrides.

    Args:
        overrides: Current MCP overrides.

    Returns:
        Lockfile MCP data.
    """
    return {"servers": {key: known_fields(value) for key, value in overrides.items()}}


def _remove_previous_fields(
    mcp_servers: MutableMapping[str, Any],
    previous_lock: Mapping[str, Any],
) -> None:
    """Remove fields previously generated by codexmgr.

    Args:
        mcp_servers: Mutable local Codex mcp_servers table.
        previous_lock: Previous codexmgr lock data.
    """
    previous_servers = previous_lock.get("mcp", {}).get("servers", {})
    if not isinstance(previous_servers, Mapping):
        return
    for server_id, fields in previous_servers.items():
        target = mcp_servers.get(server_id)
        if not isinstance(target, MutableMapping) or not isinstance(fields, Mapping):
            continue
        for field in fields:
            target.pop(field, None)
        if not target:
            mcp_servers.pop(server_id, None)
