"""Shared generated-state data structures for project apply and sync."""

from dataclasses import dataclass
from pathlib import Path
from typing import Any

from ..skills.copies import SkillCopy


@dataclass(frozen=True)
class GeneratedFile:
    """Expected content for one codexmgr-managed generated file.

    Attributes:
        path: Filesystem path to the generated file.
        content: Expected UTF-8 text content for the generated file.
    """

    path: Path
    content: str


@dataclass(frozen=True)
class ProjectBuild:
    """Expected generated project state.

    Attributes:
        files: Text files generated by codexmgr.
        copy_files: Expected files inside managed directory copies.
        skill_copies: Managed skill directories to overlay-copy on apply.
        obsolete_skill_copy_targets: Previous managed skill directories to remove.
        hook_copies: Managed hook directories to overlay-copy on apply.
        obsolete_hook_copy_targets: Previous managed hook directories to remove.
        obsolete_file_targets: Previously generated files to remove.
    """

    files: list[GeneratedFile]
    copy_files: list[Any]
    skill_copies: list[SkillCopy]
    obsolete_skill_copy_targets: list[Path]
    hook_copies: list[Any]
    obsolete_hook_copy_targets: list[Path]
    obsolete_file_targets: list[Path]
